objects/ApplicationLog__c.object
<CustomObject>
    <description>Stores debug, info and error messages for support purposes</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Attachment__c.object
<CustomObject>
    <description>The documents uploaded as part of a case. These are physically stored in an external repository. Attachments object only contains the link to the external repository.</description>
    <fields>
        <fullName>CaseItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item</label>
        <referenceTo>CaseItem__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>AT-{000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Attachments__c</fullName>
        <description>Count of Attachments</description>
        <label>Attachments</label>
        <summaryForeignKey>Attachment__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CaseReasons__c</fullName>
        <description>Custom Case Reasons - for field dependency on status</description>
        <label>Case Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No application for internal review made</fullName>
                </value>
                <value>
                    <fullName>Review Declined - No Work Capacity Decision</fullName>
                </value>
                <value>
                    <fullName>Review Declined - No internal review</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Out of time application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Frivolous application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Vexatious application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Expired application</fullName>
                </value>
                <value>
                    <fullName>Review Withdrawn - Insurer withdrew WCD</fullName>
                </value>
                <value>
                    <fullName>Review Withdrawn - Worker withdrew MR</fullName>
                </value>
                <value>
                    <fullName>Same Decision - No new information</fullName>
                </value>
                <value>
                    <fullName>Same Decision - New information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Better for worker - No new information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Better for worker - New information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Worse for worker - No new information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Worse for worker - New information</fullName>
                </value>
                <value>
                    <fullName>No Internal review &amp; 30 days has not lapsed since application for internal review was made</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Deleted draft application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DRS_DeleteExpired_Batch.cls
public class DRS_DeleteExpired_Batch implements Database.Batchable<SObject>, System.Schedulable, Database.AllowsCallouts {
    private Integer numberOfDays {get;set;}
    
    public DRS_DeleteExpired_Batch() {
        this.numberOfDays = 1;
    }
    
    public DRS_DeleteExpired_Batch(Integer numberOfDays) {
        this.numberOfDays = numberOfDays;
    }
    
    public List<Case> start(Database.BatchableContext objBatchableContext) {
        String caseSOQL = '' +
            ' Select Id, Status, ' +
            ' (Select Id From CaseItems__r), ' +
            ' (Select Id From Attachments__r) ' +
            ' From Case ' +
            ' Where (Status = \'' + DRS_CaseService.CaseStatusClosed + '\' And CaseReasons__c = \'' + DRS_CaseService.CaseReasonExpired + '\') ' +
            ' And ClosedDate >= Last_N_Days:' + this.numberOfDays + ' ';
        return Database.query(caseSOQL);
    }
    
    public void execute(Database.BatchableContext objBatchableContext, List<Case> listCases) {
        try {
            List<SObject> listObjectsToDelete = new List<SObject>();
            List<SObject> listObjectsToUpdate = new List<SObject>();
            List<ApplicationLog__c> listApplicationLogsToInsert = new List<ApplicationLog__c>();
            String signedURL;
            for(Case objCase : listCases) {
                signedURL = DRS_S3Service.getSignedDeleteUrl(objCase.Id);
                HttpResponse objHttpResponse = DRS_GlobalUtility.callRESTAPI(DRS_GlobalUtility.RESTDeleteMethod, signedURL, null, null);
                
                if(objHttpResponse.getStatusCode() == 204) {
                    for(CaseItem__c objCaseItem : objCase.CaseItems__r) {
                        listObjectsToDelete.add(objCaseItem);
                    }
                    for(Attachment__c objAttachment : objCase.Attachments__r) {
                        listObjectsToDelete.add(objAttachment);
                    }
                    if(objCase.Status != DRS_CaseService.CaseStatusClosed) {
                        objCase.Status = DRS_CaseService.CaseStatusClosed;
                        objCase.CaseReasons__c = DRS_CaseService.CaseReasonDeletedDraft;
                        listObjectsToUpdate.add(objCase);
                    }
                }
                else {
                    listApplicationLogsToInsert.add(DRS_GlobalUtility.getAppliationLogError(
                        objHttpResponse.getBody(), DRS_GlobalUtility.RESTDeleteMethod + ' ' + signedURL, String.valueOf(objHttpResponse.getStatusCode()), objCase.Id, 'Delete attachments related to case', 'DRS_DeleteExpired_Batch', 'execute', ''));
                }
            }
            
            System.debug('---DRS_DeleteExpired_Batch:execute:listObjectsToDelete:' + listObjectsToDelete);
            System.debug('---DRS_DeleteExpired_Batch:execute:listApplicationLogsToInsert:' + listApplicationLogsToInsert);
            
            if(listObjectsToDelete.size() > 0) {
                listObjectsToDelete.sort();
                Delete listObjectsToDelete;
            }
            if(listObjectsToUpdate.size() > 0) {
                listObjectsToUpdate.sort();
                Update listObjectsToUpdate;
            }
            if(listApplicationLogsToInsert.size() > 0) {
                listApplicationLogsToInsert.sort();
                Insert listApplicationLogsToInsert;
            }
        }
        catch(Exception excep) {
            DRS_GlobalUtility.handleServiceException(excep, 'DRS_DeleteExpired_Batch', 'execute');
        }
    }
    
    public void finish(Database.BatchableContext objBatchableContext) {
        
    }
    
    public void execute(SchedulableContext objSchedulableContext) {
        Database.executeBatch(new DRS_DeleteExpired_Batch(), 30);
    }
    
}