objects/Attachment__c.object
<CustomObject>
    <description>The documents uploaded as part of a case. These are physically stored in an external repository. Attachments object only contains the link to the external repository.</description>
    <fields>
        <fullName>FileName__c</fullName>
        <description>The name of the attached file.</description>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Key__c</fullName>
        <description>The Case, Case Item and Attachment IDs combination for the key of document stored in S3.</description>
        <inlineHelpText>The Case, Case Item and Attachment IDs combination for the key of document stored in S3.</inlineHelpText>
        <label>S3 Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>AT-{000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Configuration__c.object
<CustomObject>
    <description>An object to store the configurations for different projects. The fields created for this object can be shared among different projects. The name of the record defines the project for which configurations are defined.</description>
    <fields>
        <fullName>EC2ServerPath__c</fullName>
        <description>The path of the EC2 server.</description>
        <inlineHelpText>The path of the EC2 server.</inlineHelpText>
        <label>EC2 Server Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteId1__c</fullName>
        <description>Id of a site used for community. There could be more than 1 communities for a project. New fields with increasing order should be created for the each new community for a project.</description>
        <label>Site Id 1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DRS_ViewDocument_CX.cls
public with sharing class DRS_ViewDocument_CX {
    public String url {get; set;}
    public Boolean isMultimedia {get;set;}
    public String videoMultiMediaURL {get;set;}
    public String audioMultiMediaURL {get;set;}
    
    public DRS_ViewDocument_CX(ApexPages.StandardController stdController) {
        Configuration__c objMRSConfiguration = DRS_GlobalUtility.getMRSConfiguration();
        DomainSite objWorkerDomainSite = DRS_GlobalUtility.getDomainSiteForId(objMRSConfiguration.SiteId1__c);
        Boolean isSalesforceInternalUser = DRS_ContactService.isSalesforceInternalUser(UserInfo.getUserId());
        Attachment__c objAttachment = (Attachment__c)stdController.getRecord();
        objAttachment = [Select Id, Filename__c, S3Key__c from Attachment__c where Id =:objAttachment.Id];
        Organization objOrganization = [Select IsSandbox From Organization Limit 1];
        
        String fileExtension = objAttachment.FileName__c.subString(objAttachment.FileName__c.lastIndexOf('.') + 1);
        fileExtension = fileExtension.toLowerCase();
        String signedURL = DRS_S3Service.getSignedDownloadUrl(objAttachment.S3Key__c);
        List<String> listDownloadedExtensions = new List<String>();
        Boolean downloadMedia = false;
        
        listDownloadedExtensions.add('mkv');
        listDownloadedExtensions.add('flv');
        listDownloadedExtensions.add('vob');
        listDownloadedExtensions.add('drc');
        listDownloadedExtensions.add('gif');
        listDownloadedExtensions.add('gifv');
        listDownloadedExtensions.add('mng');
        listDownloadedExtensions.add('avi');
        listDownloadedExtensions.add('mov');
        listDownloadedExtensions.add('qt');
        listDownloadedExtensions.add('wmv');
        listDownloadedExtensions.add('yuv');
        listDownloadedExtensions.add('rm');
        listDownloadedExtensions.add('rmvb');
        listDownloadedExtensions.add('asf');
        listDownloadedExtensions.add('amv');
        listDownloadedExtensions.add('mpg');
        listDownloadedExtensions.add('mp2');
        listDownloadedExtensions.add('mpeg');
        listDownloadedExtensions.add('mpe');
        listDownloadedExtensions.add('mpv');
        listDownloadedExtensions.add('m2v');
        listDownloadedExtensions.add('svi');
        listDownloadedExtensions.add('3gp');
        listDownloadedExtensions.add('3g2');
        listDownloadedExtensions.add('mxf');
        listDownloadedExtensions.add('roq');
        listDownloadedExtensions.add('nsv');
        listDownloadedExtensions.add('f4v');
        listDownloadedExtensions.add('f4p');
        listDownloadedExtensions.add('f4a');
        listDownloadedExtensions.add('f4b');
        listDownloadedExtensions.add('aa');
        listDownloadedExtensions.add('aac');
        listDownloadedExtensions.add('aax');
        listDownloadedExtensions.add('act');
        listDownloadedExtensions.add('aiff');
        listDownloadedExtensions.add('amr');
        listDownloadedExtensions.add('ape');
        listDownloadedExtensions.add('au');
        listDownloadedExtensions.add('awb');
        listDownloadedExtensions.add('dct');
        listDownloadedExtensions.add('dss');
        listDownloadedExtensions.add('dvf');
        listDownloadedExtensions.add('flac');
        listDownloadedExtensions.add('gsm');
        listDownloadedExtensions.add('iklax');
        listDownloadedExtensions.add('ivs');
        listDownloadedExtensions.add('m4a');
        listDownloadedExtensions.add('m4b');
        listDownloadedExtensions.add('mmf');
        listDownloadedExtensions.add('mpc');
        listDownloadedExtensions.add('msv');
        listDownloadedExtensions.add('opus');
        listDownloadedExtensions.add('ra');
        listDownloadedExtensions.add('rm');
        listDownloadedExtensions.add('raw');
        listDownloadedExtensions.add('sln');
        listDownloadedExtensions.add('tta');
        listDownloadedExtensions.add('vox');
        listDownloadedExtensions.add('wv');
        
        for(String downloadedExtension : listDownloadedExtensions) {
        	if(fileExtension == downloadedExtension) {
        		downloadMedia = true;
        	}
        }
        
        isMultimedia = false;
        if(fileExtension == 'ogg' || fileExtension == 'ogv' || fileExtension == 'webm' || fileExtension == 'mp4' ||
        	fileExtension == 'm4v' || fileExtension == 'm4p') {
            isMultimedia = true;
            videoMultiMediaURL = signedURL;
        }
        else if (fileExtension == 'mp3' || fileExtension == 'wav' || fileExtension == 'oga' || fileExtension == 'mogg') {
            isMultimedia = true;
            audioMultiMediaURL = signedURL;
        }
        else if (downloadMedia) {
        	this.url = signedURL;
        }
        else {
            this.url = ''
                + objMRSConfiguration.EC2ServerPath__c + '/?userId=' + UserInfo.getUserId()
                + '&userName=' + UserInfo.getName()
                + '&attachmentId=' + objAttachment.Id
                + '&communityURL=' + EncodingUtil.urlEncode(objWorkerDomainSite.Domain.Domain, 'UTF-8')
                + '&externalView=' + !isSalesforceInternalUser
                + '&isTest=' + objOrganization.IsSandbox
                + '&document=' + EncodingUtil.urlEncode(signedURL, 'UTF-8');
        }
    }
}