objects/Attachment__c.object
<CustomObject>
    <description>The documents uploaded as part of a case. These are physically stored in an external repository. Attachments object only contains the link to the external repository.</description>
    <fields>
        <fullName>CaseItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item</label>
        <referenceTo>CaseItem__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>AT-{000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CaseReasons__c</fullName>
        <description>Custom Case Reasons - for field dependency on status</description>
        <label>Case Reasons</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No application for internal review made</fullName>
                </value>
                <value>
                    <fullName>Review Declined - No Work Capacity Decision</fullName>
                </value>
                <value>
                    <fullName>Review Declined - No internal review</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Out of time application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Frivolous application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Vexatious application</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Expired application</fullName>
                </value>
                <value>
                    <fullName>Review Withdrawn - Insurer withdrew WCD</fullName>
                </value>
                <value>
                    <fullName>Review Withdrawn - Worker withdrew MR</fullName>
                </value>
                <value>
                    <fullName>Same Decision - No new information</fullName>
                </value>
                <value>
                    <fullName>Same Decision - New information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Better for worker - No new information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Better for worker - New information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Worse for worker - No new information</fullName>
                </value>
                <value>
                    <fullName>Different Decision - Worse for worker - New information</fullName>
                </value>
                <value>
                    <fullName>No Internal review &amp; 30 days has not lapsed since application for internal review was made</fullName>
                </value>
                <value>
                    <fullName>Review Declined - Deleted draft application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClaimNumber__c</fullName>
        <description>Claim Number provided by the Insurer</description>
        <externalId>true</externalId>
        <label>Claim Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateOfInjury__c</fullName>
        <description>MRS Date of Injury</description>
        <label>Date of Injury</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateWorkerReceivedIR__c</fullName>
        <description>MRS - Date Worker Received IR</description>
        <label>Date Worker  Received IR</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IRDecision__c</fullName>
        <description>MRS - IR Decision</description>
        <label>IR Decision Notice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Insurer Account Name</description>
        <label>Insurer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRSInsurerAccount__c</fullName>
        <description>MRS Insurer Account for Sharing rules</description>
        <label>MRS Insurer Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NotAWorkCapacityDecision__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type Not a Work Capacity Decision</description>
        <label>Not a Work Capacity Decision</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43AWorkCapacity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WCD Decision Type S43A - Work Capacity</description>
        <inlineHelpText>S43A - Work Capacity</inlineHelpText>
        <label>S43A Work Capacity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43BSuitableEmployment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43B - Suitable Employment</description>
        <inlineHelpText>S43B - Suitable Employment</inlineHelpText>
        <label>S43B Suitable Employment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43CAmountEarntInSE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43C - Amount earnt in SE</description>
        <inlineHelpText>S43C - Amount earnt in SE</inlineHelpText>
        <label>S43C Amount earnt in SE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43D1PIAWE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43D1 - PIAWE</description>
        <inlineHelpText>S43D1 - PIAWE</inlineHelpText>
        <label>S43D1 PIAWE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43D2CurrentWeeklyEarnings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43D2 Current Weekly Earnings</description>
        <inlineHelpText>S43D2 - Current Weekly Earnings</inlineHelpText>
        <label>S43D2 Current Weekly Earnings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43EUnableToEngageInCertainEmploy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43E - Inability to engage in certain employment</description>
        <inlineHelpText>S43E - Inability to engage in certain employment</inlineHelpText>
        <label>S43E Unable to engage in certain employ.</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S43FAnyOtherWeeklyPaymentsDecision__c</fullName>
        <defaultValue>false</defaultValue>
        <description>MRS - WDC Decision Type S43F - Any other weekly payments decision</description>
        <inlineHelpText>S43F - Any other weekly payments decision</inlineHelpText>
        <label>S43F Any other weekly payments decision</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WCDNoticeDate__c</fullName>
        <description>MRS - WCD Notice Date</description>
        <label>WCD Notice Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>CaseItemData__c</fullName>
        <description>The data received as part of the Case Item submission. The intended content of this field is a structured JSON object.</description>
        <label>Case Item Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedByName__c</fullName>
        <formula>SubmittedBy__r.FirstName + &apos; &apos; + SubmittedBy__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submitted By Name</label>
        <type>Text</type>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InterpreterRequired__c</fullName>
        <description>Accessibility Field: Do you require an interpreter?</description>
        <label>Interpreter Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KnownWorkerDisabilities__c</fullName>
        <description>Does the worker have any disabilities we need to know about when communicating with them?</description>
        <label>Known Worker Disabilities</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Worker requires an interpreter who speaks the entered language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>Chinese (Traditional)</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Worker</fullName>
                </value>
                <value>
                    <fullName>Legal Rep</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Sole Practitioner</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                    <isActive>false</isActive>
                    <label>Lawyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DRS_CaseItemForm_CC.cls
public without sharing class DRS_CaseItemForm_CC {
    
    @AuraEnabled
    public static List<Account> getInsurersByName(String insurerName) {
        return DRS_AccountService.getActiveInsurersByName(insurerName);
    }
    
    @AuraEnabled
    public static String getCategories() {
        List<Snippet__c> listSnippets;
        List<String> listPermissionSetNames = new List<String>();
        if(DRS_ContactService.isSalesforceInternalUser(UserInfo.getUserId())) {
            listPermissionSetNames.add(DRS_ContactService.PermissionSetMRSInternalUser);
        }
        else {
            listPermissionSetNames = DRS_ContactService.getPermissionSetsForUser(UserInfo.getUserId());
        }
        System.debug('---DRS_CaseItemForm_CC:getCategories:listPermissionSetNames:' + listPermissionSetNames);
        listSnippets = DRS_GlobalUtility.getSnippetsForLocation(DRS_GlobalUtility.LocationMRSUpload, listPermissionSetNames);
        System.debug('---DRS_CaseItemForm_CC:getCategories:listSnippets:' + JSON.serializePretty(listSnippets));
        return JSON.serialize(listSnippets);
    }
    
    @AuraEnabled
    public static String initiateNewCaseItem() {
        try{
            Boolean isSalesforceInternalUser = DRS_ContactService.isSalesforceInternalUser(UserInfo.getUserId());
            Boolean isWorkerUser = false;
            Contact objContact;
            
            if(!isSalesforceInternalUser) {
                objContact = DRS_ContactService.getContactForUser();
            }
            
            try {
                isWorkerUser = DRS_ContactService.isWorkerUser(UserInfo.getUserId());
            }
            catch (Exception excep) {} ///Do nothing as an exception is expected for a non community user
            
            if(isSalesforceInternalUser || 
               isWorkerUser || 
               (objContact != null && String.isNotBlank(objContact.Role__c) && objContact.Role__c.contains(DRS_ContactService.ContactRoleLegalRep))) 
            {
                Case objCase = DRS_CaseService.createMRSCase();
                CaseItem__c objCaseItem = DRS_CaseService.createWorkerCaseItem(objCase.Id);
                
                DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = new DRS_GlobalWrapper.CaseItemJSON();
                if(!isSalesforceInternalUser) {
                    objCaseItemFormJSON.contactId = objContact.Id;
                    objCaseItemFormJSON.title = (String.isNotBlank(objContact.Salutation) ? objContact.Salutation : 'Mr.');
                    objCaseItemFormJSON.givenName = objContact.FirstName;
                    objCaseItemFormJSON.surname = objContact.LastName;
                    objCaseItemFormJSON.dob = String.valueOf(objContact.Birthdate);
                    objCaseItemFormJSON.contact = objContact.Phone;
                    objCaseItemFormJSON.emailAddress = objContact.Email;
                    objCaseItemFormJSON.postal = objContact.MailingStreet;
                    objCaseItemFormJSON.suburb = objContact.MailingCity;
                    objCaseItemFormJSON.state = objContact.MailingState;
                    objCaseItemFormJSON.postcode = objContact.MailingPostalCode;
                    objCaseItemFormJSON.interpreter = objContact.InterpreterRequired__c;
                    objCaseItemFormJSON.language = objContact.Language__c;
                    objCaseItemFormJSON.disabilities = objContact.KnownWorkerDisabilities__c;
                }
                objCaseItemFormJSON.isLocked = false;
                objCaseItemFormJSON.caseOrigin = 'Post';
                objCaseItemFormJSON.caseItemId = objCaseItem.Id;
                objCaseItemFormJSON.caseNumber = objCase.CaseNumber;
                objCaseItemFormJSON.claimNo = objCase.ClaimNumber__c;
                objCaseItemFormJSON.caseId = objCase.Id;
                objCaseItemFormJSON.status = DRS_CaseService.CaseItemStatusDraft;
                return JSON.serialize(objCaseItemFormJSON);
            }
            throw new AuraHandledException(DRS_MessageService.getMessage(DRS_MessageService.AuthorizationError));
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'initiateNewCaseItem');
        }
    }
    
    @AuraEnabled
    public static String getExistingCaseItem(String caseItemId) {
        try {
            CaseItem__c objCaseItem = DRS_CaseService.getCaseItemDetails(caseItemId);
            Case objCase = DRS_CaseService.getCaseDetails(objCaseItem.Case__c);
            
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCase.Id);
            Boolean isInternalUser = DRS_ContactService.isSalesforceInternalUser(UserInfo.getUserId());
            Contact objContact;
            if(!isInternalUser) {
                objContact = DRS_ContactService.getContactForUser(UserInfo.getUserId());
            }
            
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = new DRS_GlobalWrapper.CaseItemJSON();
            objCaseItemFormJSON.submittedBy = objCaseItem.SubmittedByName__c;
            objCaseItemFormJSON.submittedDate = objCaseItem.CreatedDate.format(DRS_GlobalUtility.DateFormat);
            objCaseItemFormJSON.caseItemData = objCaseItem.CaseItemData__c;
            objCaseItemFormJSON.caseItemId = objCaseItem.Id;
            objCaseItemFormJSON.status = objCaseItem.Status__c;
            objCaseItemFormJSON.caseNumber = objCase.CaseNumber;
            objCaseItemFormJSON.insurer = new DRS_GlobalWrapper.InsurerJSON();
			objCaseItemFormJSON.insurer.name = objCase.MRSInsurerAccount__c;
			objCaseItemFormJSON.insurer.id = objCase.Insurer__c;
            objCaseItemFormJSON.claimNo = objCase.ClaimNumber__c;
            objCaseItemFormJSON.caseId = objCase.Id;
            objCaseItemFormJSON.workerName = objCase.Contact.Name;
            objCaseItemFormJSON.workCapacity = objCase.S43AWorkCapacity__c;
            objCaseItemFormJSON.suitableEmployment = objCase.S43BSuitableEmployment__c;
            objCaseItemFormJSON.amountEarntInSE = objCase.S43CAmountEarntInSE__c;
            objCaseItemFormJSON.piawe = objCase.S43D1PIAWE__c;
            objCaseItemFormJSON.currentWeeklyEarnings = objCase.S43D2CurrentWeeklyEarnings__c;
            objCaseItemFormJSON.unableToEngageInCertainEmploy = objCase.S43EUnableToEngageInCertainEmploy__c;
            objCaseItemFormJSON.anyOtherWeeklyPaymentDecision = objCase.S43FAnyOtherWeeklyPaymentsDecision__c;
            objCaseItemFormJSON.caseReasons = objCase.CaseReasons__c;
            objCaseItemFormJSON.notAWorkerCapacityDecision = objCase.NotAWorkCapacityDecision__c;
            objCaseItemFormJSON.dateOfInjury = DRS_GlobalUtility.convertDateToString(objCase.DateOfInjury__c);
            objCaseItemFormJSON.workCapacityDecisionDate = DRS_GlobalUtility.convertDateToString(objCase.WCDNoticeDate__c);
            objCaseItemFormJSON.internalReviewDecisionDate = DRS_GlobalUtility.convertDateToString(objCase.IRDecision__c);
            objCaseItemFormJSON.supportingDocumentAttachedDate = DRS_GlobalUtility.convertDateToString(objCase.DateWorkerReceivedIR__c);
            
            objCaseItemFormJSON.isLocked = false;
            if(!isInternalUser) {
                objCaseItemFormJSON.isLocked = true;
                if(objCaseItem.RoleGroup__c.contains(objContact.Account.Type)){
                    objCaseItemFormJSON.isLocked = false;
                }
            }
            
            objCaseItemFormJSON.attachments = new List<DRS_GlobalWrapper.AttachmentJSON>();
            DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = new DRS_GlobalWrapper.AttachmentJSON();
            for(Attachment__c objAttachment : objCaseItem.Attachments__r) {
                if(isInternalUser == false && objAttachment.ExternallyVisible__c == false) {
                    continue;
                }
                objAttachmentJSON = new DRS_GlobalWrapper.AttachmentJSON(); 
                objAttachmentJSON.category = objAttachment.CategoryA__c;
                objAttachmentJSON.tier2 = objAttachment.CategoryB__c;
                objAttachmentJSON.tier3 = objAttachment.CategoryC__c;
                objAttachmentJSON.author = objAttachment.Author__c;
                objAttachmentJSON.dateOfDocument = DRS_GlobalUtility.convertDateToString(objAttachment.AuthoredDate__c);
                objAttachmentJSON.description = objAttachment.Description__c;
                objAttachmentJSON.name = objAttachment.FileName__c;
                objAttachmentJSON.caseId = objAttachment.Case__c;
                objAttachmentJSON.caseItemId = objAttachment.CaseItem__c;
                objAttachmentJSON.viewURL = objAttachment.S3Key__c;
                objAttachmentJSON.attachmentId = objAttachment.Id;
                objCaseItemFormJSON.attachments.add(objAttachmentJSON);
            }
            
            System.debug('---DRS_CaseItemForm_CC:getExistingCaseItem:objCaseItemFormJSON:' + JSON.serializePretty(objCaseItemFormJSON));
            return JSON.serialize(objCaseItemFormJSON);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'getExistingCaseItem');
        }
    }
    
    @AuraEnabled
    public static String saveWorkerCaseItem(String caseItemJson) {
        try {
            System.debug('---DRS_CaseItemForm_CC:saveWorkerCaseItem:caseItemJson:' + caseItemJson);
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = (DRS_GlobalWrapper.CaseItemJSON)JSON.deserialize(caseItemJson, DRS_GlobalWrapper.CaseItemJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCaseItemFormJSON.caseId);
            
           return DRS_CaseService.submitWorkerCaseItem(caseItemJson);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'saveWorkerCaseItem');
        }
    }
    
    @AuraEnabled
    public static String saveInsurerCaseItem(String caseItemJson) {
    	try {
            System.debug('---DRS_CaseItemForm_CC:saveInsurerCaseItem:caseItemJson:' + caseItemJson);
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = (DRS_GlobalWrapper.CaseItemJSON)JSON.deserialize(caseItemJson, DRS_GlobalWrapper.CaseItemJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCaseItemFormJSON.caseId);
            
            return DRS_CaseService.submitInsurerCaseItem(caseItemJson);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'saveInsurerCaseItem');
        }
    }
    
    @AuraEnabled
    public static String savePauseWorkerCaseItem(String caseItemJson) {
        try {
            System.debug('---DRS_CaseItemForm_CC:savePauseWorkerCaseItem:caseItemJson:' + caseItemJson);
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = (DRS_GlobalWrapper.CaseItemJSON)JSON.deserialize(caseItemJson, DRS_GlobalWrapper.CaseItemJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCaseItemFormJSON.caseId);
            
            return DRS_CaseService.saveWorkerCaseItem(caseItemJson);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'savePauseWorkerCaseItem');
        }
    }
    
    @AuraEnabled
    public static String savePauseInsurerCaseItem(String caseItemJson) {
        try {
            System.debug('---DRS_CaseItemForm_CC:savePauseInsurerCaseItem:savePauseInsurerCaseItem:' + caseItemJson);
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = (DRS_GlobalWrapper.CaseItemJSON)JSON.deserialize(caseItemJson, DRS_GlobalWrapper.CaseItemJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCaseItemFormJSON.caseId);
            
            return DRS_CaseService.saveInsurerCaseItem(caseItemJson);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'savePauseInsurerCaseItem');
        }
    }
    
    @AuraEnabled 
    public static String saveAllocationChecklist(string caseItemJson) {
        try {
            System.debug('---DRS_CaseItemForm_CC:saveAllocationChecklist:caseItemJson:' + caseItemJson);
            DRS_CaseService.submitAllocationChecklist(caseItemJson);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'saveAllocationChecklist');
        }
        return 'Success';
    }
    
    @AuraEnabled
    public static String saveAdditionalInformation(String additionalInformationJSON) {
        try {
            DRS_GlobalWrapper.CaseItemJSON objCaseItemFormJSON = (DRS_GlobalWrapper.CaseItemJSON)JSON.deserialize(additionalInformationJSON, DRS_GlobalWrapper.CaseItemJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objCaseItemFormJSON.caseId);
            
            System.debug('---DRS_CaseItemForm_CC:saveAdditionalInformation:additionalInformationJSON' + additionalInformationJSON);
            return DRS_CaseService.saveAdditionalInformation(additionalInformationJSON);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'saveAllocationChecklist');
        }
    }
    
    @AuraEnabled
    public static String getDateDifferenceWithHolidays(String startingDate, String numberOfDays){
        if(String.isNotBlank(startingDate)) {
            try {
                Date startingDateDate = DRS_GlobalUtility.getDateFromString(startingDate);
                DateTime startingDateDateTime = DateTime.newInstance(startingDateDate, DateTime.now().time());
                DateTime endingDateTime = DRS_GlobalUtility.getDateDifferenceWithNextWorkingDay(startingDateDateTime, Integer.valueOf(numberOfDays));
                return DRS_GlobalUtility.convertDateToString(endingDateTime.date());
            }
            catch(Exception excep) {
                return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'getDateDifferenceWithHolidays');
            }
        }
        return startingDate;
    }
    
    @AuraEnabled
    public static String getInternalUsers(String partialName) {
        try{
            System.debug('---DRS_CaseItemForm_CC:getInternalUsers:userName' + partialName);
            
            if(DRS_ContactService.isSalesforceInternalUser(UserInfo.getUserId())) {
                List<User> listUsers = DRS_ContactService.getUsersForPartialNames(partialName);
                System.debug('---DRS_CaseItemForm_CC:getInternalUsers:listUsers' + JSON.serializePretty(listUsers));
                return JSON.serialize(listUsers);
            }
        }
        catch(Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'getInternalUsers');
        }
        return JSON.serialize(new List<User>());
    }
    
    @AuraEnabled
    public static String addAttachment(String attachmentJSON) {
        System.debug('---DRS_CaseItemForm_CC:addAttachment:attachmentJSON:' + attachmentJSON);
        try {
            DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = (DRS_GlobalWrapper.AttachmentJSON)JSON.deserialize(attachmentJSON, DRS_GlobalWrapper.AttachmentJSON.class);
            DRS_CaseService.checkAuthorizedUser(UserInfo.getUserId(), objAttachmentJSON.caseId);
            
            return DRS_CaseService.addAttachment(attachmentJSON);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'addAttachment');
        }
    }
    
    @AuraEnabled
    public static String removeAttachment(String attachmentId) {
        try {
            DRS_CaseService.removeAttachment(attachmentId);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'removeAttachment');
        }
        return 'Success';
    }
    
    @AuraEnabled
    public static String addAttachmentAndGetSignedURL(String attachmentJSON) {
        String path;
        
        try {
            String attachmentId = DRS_CaseItemForm_CC.addAttachment(attachmentJSON);
            Attachment__c objAttachment = DRS_CaseService.getAttachmentDetails(attachmentId);
            
            path = DRS_CaseItemForm_CC.getAttachmentS3Path(objAttachment);
            String signedURL = DRS_S3Service.getSignedUploadUrl(path);
            DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = new DRS_GlobalWrapper.AttachmentJSON();
            objAttachmentJSON.attachmentId = objAttachment.Id;
            objAttachmentJSON.saveURL = signedURL;
            
            objAttachment = new Attachment__c(Id = attachmentId);
            objAttachment.S3Key__c = path;
            Update objAttachment;
            
            return JSON.serialize(objAttachmentJSON);
        }
        catch (Exception excep) {
            return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'addAttachmentAndGetSignedURL');
        }
    }
    
    /*
@AuraEnabled
public static String initiateMultipartUpload(String attachmentJSON) {
System.debug('---DRS_CaseItemForm_CC:initiateMultipartUpload:attachmentJSON:' + attachmentJSON);
String path;
String multipartUploadId;
try{
DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = (DRS_GlobalWrapper.AttachmentJSON)JSON.deserialize(attachmentJSON, DRS_GlobalWrapper.AttachmentJSON.class);
Attachment__c objAttachment = DRS_CaseService.getAttachmentDetails(objAttachmentJSON.attachmentId);
System.debug('---DRS_CaseItemForm_CC:initiateMultipartUpload:objAttachment:' + objAttachment);

path = DRS_CaseItemForm_CC.getAttachmentS3Path(objAttachment);
String signedURL = DRS_S3Service.getMultipartUploadInitiationUrl(path);
objAttachmentJSON.saveURL = signedURL;
System.debug('---DRS_CaseItemForm_CC:initiateMultipartUpload:signedURL:' + signedURL);

HttpResponse objHttpResponse = DRS_GlobalUtility.callRESTAPI(DRS_GlobalUtility.RESTPostMethod, signedURL, null, null);
System.debug('---DRS_CaseItemForm_CC:initiateMultipartUpload:objHttpResponse.getBody():' + objHttpResponse.getBody());

String xmlString = objHttpResponse.getBody();
if(String.isNotBlank(xmlString)) {
DOM.Document xmlDOC = new DOM.Document();
xmlDOC.load(xmlString);
for(Dom.XMLNode child : xmlDOC.getRootElement().getChildElements())
{
if(child.getName().toUpperCase() == 'UPLOADID') {
multipartUploadId = child.getText();
}
}
System.debug('---DRS_CaseItemForm_CC:initiateMultipartUpload:objHttpResponse.multipartUploadId:' + multipartUploadId);
if(String.isBlank(multipartUploadId)) {
DRS_CaseService.removeAttachment(objAttachmentJSON.attachmentId);
throw new DRS_GlobalException.ServiceException(DRS_MessageService.getMessage(DRS_MessageService.MultipartUploadFailed));
}

objAttachment = new Attachment__c(Id = objAttachmentJSON.attachmentId);
objAttachment.S3Key__c = path;
objAttachment.UploadId__c = multipartUploadId;
Update objAttachment;

return JSON.serialize(objAttachmentJSON);
}
else {
DRS_CaseService.removeAttachment(objAttachmentJSON.attachmentId);
throw new DRS_GlobalException.ServiceException(DRS_MessageService.getMessage(DRS_MessageService.MultipartUploadFailed));
}
}
catch (Exception excep) {
DRS_CaseService.abortMultipartUpload(attachmentJSON);
return DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'addAttachmentAndGetSignedURL');
}
}

@AuraEnabled
public static String getUploadUrlForParts(String numberOfParts, String attachmentJSON) {
DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = (DRS_GlobalWrapper.AttachmentJSON)JSON.deserialize(attachmentJSON, DRS_GlobalWrapper.AttachmentJSON.class);
Attachment__c objAttachment = DRS_CaseService.getAttachmentDetails(objAttachmentJSON.attachmentId);
List<String> listS3SignedURLs = new List<String>();
String s3SignedURL;
for(Integer counter = 1; counter <= Integer.valueOf(numberOfParts); counter++) {
s3SignedURL = DRS_S3Service.getMultipartUploadUrl(objAttachment.S3Key__c, String.valueOf(counter), objAttachment.UploadId__c);
System.debug('---DRS_CaseItemForm_CC:getUploadUrlForParts:partNumber:' + counter + ', s3SignedURL:' + s3SignedURL);
listS3SignedURLs.add(s3SignedURL);
}
System.debug('---DRS_CaseItemForm_CC:getUploadUrlForParts:listS3SignedURLs:' + listS3SignedURLs);
return JSON.serialize(listS3SignedURLs);
}

@AuraEnabled
public static void completeMultipartUpload(String attachmentJSON) {
try {
System.debug('---DRS_CaseItemForm_CC:completeMultipartUpload:attachmentJSON:' + attachmentJSON);
DRS_CaseService.completeMultipartUpload(attachmentJSON);
}
catch(Exception excep) {
DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'completeMultipartUpload');
}
}

@AuraEnabled
public static void abortMultipartUpload(String attachmentJSON) {
try {
DRS_GlobalWrapper.AttachmentJSON objAttachmentJSON = (DRS_GlobalWrapper.AttachmentJSON)JSON.deserialize(attachmentJSON, DRS_GlobalWrapper.AttachmentJSON.class);
DRS_CaseService.abortMultipartUpload(objAttachmentJSON.attachmentId);
}
catch(Exception excep) {
DRS_GlobalUtility.handleAuraException(excep, 'DRS_CaseItemForm_CC', 'abortMultipartUpload');
}
}
*/
    
    private static String getAttachmentS3Path(Attachment__c objAttachment) {
        String path = ((String)objAttachment.Case__c).left(15) + '/';
        
        if (String.isNotBlank(objAttachment.CaseItem__c)) {
            path += ((String)objAttachment.CaseItem__c).left(15) + '/';
        }
        
        path += String.valueOF(objAttachment.Id).left(15) +  '/' + EncodingUtil.urlEncode(DRS_S3Service.handleFileNameSpecialChar(objAttachment.FileName__c), 'UTF-8').replace('+', '%20');
        
        return path;
    }
}