objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>CaseItemData__c</fullName>
        <description>The data received as part of the Case Item submission. The intended content of this field is a structured JSON object.</description>
        <label>Case Item Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroup__c</fullName>
        <description>The intended audience of the Case Item to provide the required information.</description>
        <inlineHelpText>The person who you are requesting the Additional Information from. Note: This will be made visible to all Case Team Members, but editable only by the people in the Role Group selected.</inlineHelpText>
        <label>Role Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insurer</fullName>
                </value>
                <value>
                    <fullName>Worker/Worker Rep</fullName>
                </value>
                <value>
                    <fullName>Legal Firm</fullName>
                </value>
                <value>
                    <fullName>Sole Practitioner</fullName>
                </value>
                <value>
                    <fullName>Merit Review Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the Case Item</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Configuration__c.object
<CustomObject>
    <description>An object to store the configurations for different projects. The fields created for this object can be shared among different projects. The name of the record defines the project for which configurations are defined.</description>
    <fields>
        <fullName>DefaultTaskOwner__c</fullName>
        <description>Default owner of the task when it gets created</description>
        <label>Default Task Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskTemplate__c.object
<CustomObject>
    <description>A template object for creating tasks</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>The details about the task. These details will be copied to the Description (Comments) field of the Task.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the task to be created using the template.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Case_Item_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Application for merit review by SIRA form</fullName>
        <default>true</default>
        <label>Application for merit review by SIRA form</label>
    </customValue>
    <customValue>
        <fullName>Reply to an application for merit review by SIRA form</fullName>
    </customValue>
    <customValue>
        <fullName>Additional information request</fullName>
    </customValue>
    <customValue>
        <fullName>Allocation Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Peer Review</fullName>
    </customValue>
    <customValue>
        <fullName>Jurisdiction Checklist</fullName>
    </customValue>
    <masterLabel>Case Item Type</masterLabel>
</GlobalValueSet>

classes/DRS_AdditionalInformation_CX_Test.cls
@IsTest
public class DRS_AdditionalInformation_CX_Test {
    
    @TestSetup
    private static void initializeData(){
        DRS_SetupData.processData();
        DRS_TestData.createCaseWithInsurerCaseItemSubmitted();
    }
    
    private static testmethod void testConstructor() {
        Case objCase = [Select Id From Case];
        PageReference additionalInfoPage = Page.DRS_Case_AdditionalInformationCreate;
        Test.setCurrentPage(additionalInfoPage);
        
        Test.startTest();
        ApexPages.StandardController objStandardController = new ApexPages.StandardController(objCase);
        DRS_AdditionalInformation_CX objDRS_AdditionalInformation_CX = new DRS_AdditionalInformation_CX(objStandardController);
        Test.stopTest();
        
        TaskTemplate__c objTaskTemplate = DRS_CaseService.getTaskTemplateForType(DRS_CaseService.AdditionalInformationTaskType);
        Configuration__c objMRSConfiguration = DRS_GlobalUtility.getMRSConfiguration();
        
        System.assert(objDRS_AdditionalInformation_CX.objtask != null);
        System.assertEquals(objCase.Id, objDRS_AdditionalInformation_CX.objTask.WhatId);
        System.assertEquals(null, objDRS_AdditionalInformation_CX.objTask.Subject); ///Subject is set in the trigger after Task is saved
        System.assertEquals(null, objDRS_AdditionalInformation_CX.objTask.Type); ///Type is set in the trigger after Task is saved
        System.assertEquals(objMRSConfiguration.DefaultTaskOwner__c, objDRS_AdditionalInformation_CX.objTask.OwnerId);
        System.assertEquals(true, objDRS_AdditionalInformation_CX.objTask.IsReminderSet);
        System.assertEquals(DRS_CaseService.InitialTaskStatus, objDRS_AdditionalInformation_CX.objTask.Status);
    }
    
    private static testmethod void testSave() {
        Case objCase = [Select Id From Case];
        PageReference additionalInfoPage = Page.DRS_Case_AdditionalInformationCreate;
        Test.setCurrentPage(additionalInfoPage);
        String taskDescription = 'My Task Description';
        String roleGroup = 'Insurer';
        
        Test.startTest();
        ApexPages.StandardController objStandardController = new ApexPages.StandardController(objCase);
        DRS_AdditionalInformation_CX objDRS_AdditionalInformation_CX = new DRS_AdditionalInformation_CX(objStandardController);
        objDRS_AdditionalInformation_CX.objTask.Description = taskDescription;
        objDRS_AdditionalInformation_CX.objCaseItem.RoleGroup__c = roleGroup;
        objDRS_AdditionalInformation_CX.saveAdditionalInformation();
        Test.stopTest();
        
        CaseItem__c objCaseItem = [Select Id, Status__c, RoleGroup__c, CaseItemData__c From CaseItem__c Where Type__c =: DRS_CaseService.AdditionalInformationTaskType And Case__c =: objCase.Id Limit 1];
        System.assert(objCaseItem != null);
        System.assertEquals(roleGroup, objCaseItem.RoleGroup__c);
        System.assertEquals(DRS_CaseService.CaseItemStatusPending, objCaseItem.Status__c);
        DRS_GlobalWrapper.AdditionalInformationJSON objAdditionalInformationJSON = (DRS_GlobalWrapper.AdditionalInformationJSON)JSON.deserialize(objCaseItem.CaseItemData__c, DRS_GlobalWrapper.AdditionalInformationJSON.class);
        System.assertEquals(taskDescription, objAdditionalInformationJSON.requestDetails);
        
        TaskTemplate__c objTaskTemplate = DRS_CaseService.getTaskTemplateForType(DRS_CaseService.AdditionalInformationTaskType);
        Task objTask = [Select Id, Description, Type, Subject From Task Where CaseItem__c =: objCaseItem.Id];
        System.assertEquals(objTaskTemplate.Subject__c, objTask.Subject); ///Subject is set in the trigger using values from Task Template
        System.assertEquals(objTaskTemplate.Type__c, objTask.Type); ///Type is set in the trigger using values from Task Template
        System.assertEquals(objTaskTemplate.Description__c, objTask.Description); ///Description is set in the trigger using values from Task Template
    }
    
}