objects/Case.object
<CustomObject>
    <fields>
        <fullName>DateTimeCaseLodged__c</fullName>
        <description>MRS - Date/Time Case Lodged, this is is the date/time the case was submitted to MRS</description>
        <label>Date/Time Case Lodged</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommunityPageURL__c</fullName>
        <description>The URL suffix of the community page on which the Case Item should be visible</description>
        <label>Community Page URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExpiryDate__c</fullName>
        <description>The date/time on which the Case Item will be marked as expired. Automation will run to make the item expired.</description>
        <inlineHelpText>The date/time on which the Case Item will be marked as expired. Automation will run to make the item expired.</inlineHelpText>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RoleGroup__c</fullName>
        <description>The intended audience of the Case Item to provide the required information.</description>
        <inlineHelpText>The person who you are requesting the Additional Information from. Note: This will be made visible to all Case Team Members, but editable only by the people in the Role Group selected.</inlineHelpText>
        <label>Role Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insurer</fullName>
                </value>
                <value>
                    <fullName>Worker/Worker Rep</fullName>
                </value>
                <value>
                    <fullName>Legal Firm</fullName>
                </value>
                <value>
                    <fullName>Sole Practitioner</fullName>
                </value>
                <value>
                    <fullName>Merit Review Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user who submitted the Case Item</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the Case Item</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Worker</fullName>
                </value>
                <value>
                    <fullName>Legal Rep</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Sole Practitioner</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                    <isActive>false</isActive>
                    <label>Lawyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Case_Item_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Application for merit review by SIRA form</fullName>
        <default>true</default>
        <label>Application for merit review by SIRA form</label>
    </customValue>
    <customValue>
        <fullName>Reply to an application for merit review by SIRA form</fullName>
    </customValue>
    <customValue>
        <fullName>Additional information request</fullName>
    </customValue>
    <customValue>
        <fullName>Allocation Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Peer Review</fullName>
    </customValue>
    <customValue>
        <fullName>Jurisdiction Checklist</fullName>
    </customValue>
    <masterLabel>Case Item Type</masterLabel>
</GlobalValueSet>

classes/DRS_Dashboard_CC.cls
///A controller class for community dashboards
public without sharing class DRS_Dashboard_CC {
    
    ///Gets whether the logged in user is a Delegated Admin or not
    @AuraEnabled
    public static Boolean isDelegatedAdmin() {
        return DRS_ContactService.isDelegatedAdmin(UserInfo.getUserId());
    } 
    
    ///Gets lists of Case Item Lists for the Dashboard:
    ///	Draft Cases: When an application is Saved for Later by a worker. This list is only available for workers
    ///	Open Cases: When the logged in user is part of the case team of an open case
    ///	Closed Cases: When the logged in user is part of the case team of a closed case
    @AuraEnabled
    public static String getCaseItems() {
        Set<Id> setCaseIds = new Set<Id>();
        User objUser = DRS_ContactService.getUserDetails(UserInfo.getUserId());
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = new DRS_GlobalWrapper.DashboardJSON();
        objDashboardJSON.userId = UserInfo.getUserId();
        objDashboardJSON.userFirstName = objUser.FirstName;
        objDashboardJSON.userLastName = objUser.LastName;
        objDashboardJSON.openCaseItems = new List<DRS_GlobalWrapper.CaseItemJSON>();
        objDashboardJSON.pendingCaseItems = new List<DRS_GlobalWrapper.CaseItemJSON>();
        objDashboardJSON.draftCaseItems = new List<DRS_GlobalWrapper.CaseItemJSON>();
        objDashboardJSON.closedCaseItems = new List<DRS_GlobalWrapper.CaseItemJSON>();
        DRS_GlobalWrapper.CaseItemJSON objCaseItemJSON = new DRS_GlobalWrapper.CaseItemJSON();
        
        Contact objContact = DRS_ContactService.getContactForUser();
        if(String.isNotBlank(objContact.Role__c) && 
           (objContact.Role__c.contains(DRS_ContactService.ContactRoleWorker) || objContact.Role__c.contains(DRS_ContactService.ContactRoleLegalRep))) {
               objDashboardJSON.showNewApplication = true;
        }
        
        List<Case> listCases = DRS_CaseService.getOpenCasesForUser(UserInfo.getUserId());
        List<Case> listClosedCases = DRS_CaseService.getClosedCasesForUser(UserInfo.getUserId());
        List<CaseItem__c> listPendingCaseItems = new List<CaseItem__c>();
        Boolean isWorker = DRS_ContactService.isWorkerUser(UserInfo.getUserId());
        Boolean isPending = false;
        
        for(Case objCase : listCases) {
            isPending = false;
            
            for(CaseItem__c objCaseItem : objCase.CaseItems__r) {
                if((objCaseItem.Status__c == DRS_CaseService.CaseItemStatusPending || objCaseItem.Status__c == DRS_CaseService.CaseItemStatusDraft) 
                   && String.isNotBlank(objCaseItem.RoleGroup__c)
                   && (objCaseItem.RoleGroup__c.contains(objContact.Account.Type))) 
                {
                    objCaseItemJSON = new DRS_GlobalWrapper.CaseItemJSON();
                    objCaseItemJSON.caseItemId = objCaseItem.Id;
                    objCaseItemJSON.caseId = objCase.Id;
                    objCaseItemJSON.caseNumber = objCase.CaseNumber;
                    objCaseItemJSON.submittedBy = objCase.Contact.Name;
                    objCaseItemJSON.submittedDate = (objCase.DateTimeCaseLodged__c != null ? objCase.DateTimeCaseLodged__c.format(DRS_GlobalUtility.DateTimeFormat) : '');
                    objCaseItemJSON.status = objCase.Status;
                    objCaseItemJSON.communityPageURL = objCaseItem.CommunityPageURL__c;
                    objCaseItemJSON.createdDate = objCaseItem.CreatedDate.format(DRS_GlobalUtility.DateTimeFormat);
                    objCaseItemJSON.caseItemType = objCaseItem.Type__c;
                    
                    if(objCaseItem.Type__c == DRS_CaseService.WorkerCaseItemType) {
                        if(objCaseItem.ExpiryDate__c != null) {
                            objCaseItemJSON.remainingTimeToExpire = String.valueOf(Date.today().daysBetween(objCaseItem.ExpiryDate__c.date()));
                        }
                        objDashboardJSON.draftCaseItems.add(objCaseItemJSON);
                    }
                    else {
                        objDashboardJSON.pendingCaseItems.add(objCaseItemJSON);
                    }
                    isPending = true;
                    break;
                }
                else if(objCaseItem.Status__c == DRS_CaseService.CaseItemStatusExpired) {
                    isPending = true;
                    break;
                }
            }
            
            if(!isPending && objCase.Status != DRS_CaseService.CaseStatusDraft) {
                objCaseItemJSON = new DRS_GlobalWrapper.CaseItemJSON();
                objCaseItemJSON.caseId = objCase.Id;
                objCaseItemJSON.caseNumber = objCase.CaseNumber;
                objCaseItemJSON.submittedBy = objCase.Contact.Name;
                objCaseItemJSON.submittedDate = (objCase.DateTimeCaseLodged__c != null ? objCase.DateTimeCaseLodged__c.format(DRS_GlobalUtility.DateTimeFormat) : '');
                objCaseItemJSON.status = objCase.Status;
                objDashboardJSON.openCaseItems.add(objCaseItemJSON);
            }
        }
        
        ///Author Jun ZHOU
        ///Return Close Case Items
        if(listClosedCases != null && !listClosedCases.isEmpty()) {
            for(Case objCase : listClosedCases) {
                objCaseItemJSON = new DRS_GlobalWrapper.CaseItemJSON();
                objCaseItemJSON.caseId = objCase.Id;
                objCaseItemJSON.caseNumber = objCase.CaseNumber;
                objCaseItemJSON.submittedBy = objCase.Contact.Name;
                objCaseItemJSON.submittedDate = (objCase.DateTimeCaseLodged__c != null ? objCase.DateTimeCaseLodged__c.format(DRS_GlobalUtility.DateTimeFormat) : '');
                objCaseItemJSON.status = objCase.Status;
                objDashboardJSON.closedCaseItems.add(objCaseItemJSON);
            }
        }
        
        System.debug('---DRS_Dashboard_CC:getCaseItems:objDashboardJSON:' + JSON.serialize(objDashboardJSON));
        return JSON.serialize(objDashboardJSON);
    }
    
    ///Deletes the Case Item
    /// Calls the customization to delete Case Items, Attachments
    //	The customization calls S3 to delete the Attachments from S3
    @AuraEnabled
    public static void deleteDrafCaseItem(String caseId) {
        try {
            DRS_CaseService.deleteDraftCase(caseId);
        }
        catch(Exception excep) {
            DRS_GlobalUtility.handleAuraException(excep, 'DRS_Dashboard_CC', 'deleteDrafCaseItem');
        }
    }
}