objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>CaseItemData__c</fullName>
        <description>The data received as part of the Case Item submission. The intended content of this field is a structured JSON object.</description>
        <label>Case Item Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommunityPageURL__c</fullName>
        <description>The URL suffix of the community page on which the Case Item should be visible</description>
        <label>Community Page URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <description>The date/time on which the Case Item is due to be submitted.</description>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the Case Item</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Configuration__c.object
<CustomObject>
    <description>An object to store the configurations for different projects. The fields created for this object can be shared among different projects. The name of the record defines the project for which configurations are defined.</description>
    <fields>
        <fullName>DefaultTaskOwner__c</fullName>
        <description>Default owner of the task when it gets created</description>
        <label>Default Task Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskTemplate__c.object
<CustomObject>
    <description>A template object for creating tasks</description>
    <fields>
        <fullName>CommunityPageURL__c</fullName>
        <description>This is the URL of the page within the community that a user would be directed to upon opening the case item</description>
        <inlineHelpText>This is the URL of the page within the community that a user would be directed to upon opening the case item</inlineHelpText>
        <label>Community Page URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DaysUntilDueDate__c</fullName>
        <description>The number of days until the task is due.</description>
        <label>Days Until Due Date</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the task to be created using the template.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Case_Item_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Application for merit review by SIRA form</fullName>
        <default>true</default>
        <label>Application for merit review by SIRA form</label>
    </customValue>
    <customValue>
        <fullName>Reply to an application for merit review by SIRA form</fullName>
    </customValue>
    <customValue>
        <fullName>Additional information request</fullName>
    </customValue>
    <customValue>
        <fullName>Allocation Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Peer Review</fullName>
    </customValue>
    <customValue>
        <fullName>Jurisdiction Checklist</fullName>
    </customValue>
    <masterLabel>Case Item Type</masterLabel>
</GlobalValueSet>

classes/DRS_AdditionalInformation_CX.cls
public without sharing class DRS_AdditionalInformation_CX {
    
    public Task objtask {get;set;}
    public CaseItem__c objCaseItem {get;set;}
    
    private string caseId;    
    private ApexPages.StandardController objStandardController;
    
    public DRS_AdditionalInformation_CX(ApexPages.StandardController objStandardController) {
        this.objStandardController = objStandardController;
        this.caseId = objStandardController.getRecord().Id;
        
        TaskTemplate__c objTaskTemplate = DRS_CaseService.getTaskTemplateForType(DRS_CaseService.AdditionalInformationTaskType);
        Configuration__c objMRSConfiguration = DRS_GlobalUtility.getMRSConfiguration();
        
        this.objTask = new Task();
        this.objTask.TaskTemplate__c = objTaskTemplate.Id;
        this.objTask.WhatId = caseId;
        this.objTask.OwnerId = objMRSConfiguration.DefaultTaskOwner__c;
        this.objTask.IsReminderSet  = true;
        this.objTask.ReminderDateTime = this.objTask.ActivityDate;
        this.objTask.Status = DRS_CaseService.InitialTaskStatus;
        this.objTask.IsVisibleInSelfService = true;
        
        this.objCaseItem = new CaseItem__c();
        this.objCaseItem.Case__c = caseId;
        this.objCaseItem.Type__c = DRS_CaseService.AdditionalInformationTaskType;
        this.objCaseItem.Status__c = DRS_CaseService.CaseItemStatusPending;
        this.objCaseItem.CommunityPageURL__c = objTaskTemplate.CommunityPageURL__c;
        this.objCaseItem.DueDate__c = Date.Today().addDays(objTaskTemplate.DaysUntilDueDate__c.intValue());
    }
    
    public PageReference saveAdditionalInformation() {
        DRS_GlobalWrapper.AdditionalInformationJSON objAdditionalInformationJSON = new DRS_GlobalWrapper.AdditionalInformationJSON();
        objAdditionalInformationJSON.requestDetails = objTask.Description;
        this.objCaseItem.CaseItemData__c = JSON.serializePretty(objAdditionalInformationJSON);
        this.objCaseItem.DueDate__c = objTask.ActivityDate;
        Insert this.objCaseItem;
        
        this.objTask.CaseItem__c = this.objCaseItem.Id;
        Insert this.objTask;
        
        DRS_CaseService.sendEmailsToAllCaseTeamMembers(DRS_CaseService.EmailAdditionalInformationRequired, this.caseId, null);
        
        return null;
    }
    
}