objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Merit_Review_Service</fullName>
        <active>true</active>
        <businessProcess>Merit Review Service</businessProcess>
        <description>Merit Review Service (Do not change name, referenced in Process)</description>
        <label>Merit Review Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseTeamRoleAssociation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A mapping of the association of Case Team Roles and Role Groups</description>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>The value of Type field on Account standard object</description>
        <label>Account Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseTeamRole__c</fullName>
        <label>Case Team Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactRole__c</fullName>
        <label>Contact Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Team Role Association</label>
</CustomObject>

objects/Configuration__c.object
<CustomObject>
    <description>An object to store the configurations for different projects. The fields created for this object can be shared among different projects. The name of the record defines the project for which configurations are defined.</description>
    <fields>
        <fullName>CaseOwner__c</fullName>
        <description>The default owner id for the case.</description>
        <label>Case Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunityAccountOwner__c</fullName>
        <description>The default owner of the accounts which are created for community users.</description>
        <label>Community Account Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefaultTaskOwner__c</fullName>
        <description>Default owner of the task when it gets created</description>
        <label>Default Task Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EC2ServerPath__c</fullName>
        <description>The path of the EC2 server.</description>
        <inlineHelpText>The path of the EC2 server.</inlineHelpText>
        <label>EC2 Server Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromEmailAddress__c</fullName>
        <description>The sender of the emails going out for this project. This value will be populated as the sender of the emails.</description>
        <inlineHelpText>The sender of the emails going out for this project. This value will be populated as the sender of the emails.</inlineHelpText>
        <label>From Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfDaysToExpire__c</fullName>
        <description>The number of days before an case gets expired.</description>
        <inlineHelpText>The number of days before an item gets expired.</inlineHelpText>
        <label>Number Of Days To Expire</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>The encrypted field contains the password part of the credentials. The field is encrypted to ensure security of credentials.</description>
        <inlineHelpText>The encrypted field contains the password part of the credentials. The field is encrypted to ensure security of credentials.</inlineHelpText>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>ProfileId1__c</fullName>
        <description>The profile id placeholder which can be used to refer to specific profiles</description>
        <label>Profile Id 1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileId2__c</fullName>
        <description>The profile id placeholder which can be used to refer to specific profiles</description>
        <label>Profile Id 2</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3BucketName__c</fullName>
        <description>The bucket name in S3 where the files will be uploaded to.</description>
        <inlineHelpText>The bucket name in S3 where the files will be uploaded to.</inlineHelpText>
        <label>S3 Bucket Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3EncryptionScheme__c</fullName>
        <description>The S3 encryption scheme for pre-signed urls.</description>
        <inlineHelpText>The S3 encryption scheme for pre-signed urls.</inlineHelpText>
        <label>S3 Encryption Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3HeaderEncryptionScheme__c</fullName>
        <description>The S3 header encryption scheme for pre-signed urls.</description>
        <inlineHelpText>The S3 header encryption scheme for pre-signed urls.</inlineHelpText>
        <label>S3 Header Encryption Scheme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Host__c</fullName>
        <description>The S3 Host value for S3 uploads.</description>
        <inlineHelpText>The S3 Host value for S3 uploads.</inlineHelpText>
        <label>S3 Host</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Region__c</fullName>
        <description>The S3 Region for pre-signed urls.</description>
        <inlineHelpText>The S3 Region for pre-signed urls.</inlineHelpText>
        <label>S3 Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3ServerSideEncryptionAlgorithm__c</fullName>
        <description>The S3 server side encryption algorithm value.</description>
        <inlineHelpText>The S3 server side encryption algorithm value.</inlineHelpText>
        <label>S3 Server Side Encryption Algorithm</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Timeout__c</fullName>
        <description>The S3 timeout for pre-signed urls.</description>
        <inlineHelpText>The S3 timeout for pre-signed urls.</inlineHelpText>
        <label>S3 Timeout</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteId1__c</fullName>
        <description>Id of a site used for community. There could be more than 1 communities for a project. New fields with increasing order should be created for the each new community for a project.</description>
        <label>Site Id 1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteId2__c</fullName>
        <description>Id of a site used for community. There could be more than 1 communities for a project. New fields with increasing order should be created for the each new community for a project.</description>
        <label>Site Id 2</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>The encrypted field contains the username part of the credentials. The field is encrypted to ensure security of credentials.</description>
        <inlineHelpText>The encrypted field contains the username part of the credentials. The field is encrypted to ensure security of credentials.</inlineHelpText>
        <label>Username</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TaskTemplate__c.object
<CustomObject>
    <description>A template object for creating tasks</description>
    <fields>
        <fullName>CommunityPageURL__c</fullName>
        <description>This is the URL of the page within the community that a user would be directed to upon opening the case item</description>
        <inlineHelpText>This is the URL of the page within the community that a user would be directed to upon opening the case item</inlineHelpText>
        <label>Community Page URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DaysUntilDueDate__c</fullName>
        <description>The number of days until the task is due.</description>
        <label>Days Until Due Date</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The details about the task. These details will be copied to the Description (Comments) field of the Task.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the task to be created using the template.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Case_Item_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Application for merit review by SIRA form</fullName>
        <default>true</default>
        <label>Application for merit review by SIRA form</label>
    </customValue>
    <customValue>
        <fullName>Reply to an application for merit review by SIRA form</fullName>
    </customValue>
    <customValue>
        <fullName>Additional information request</fullName>
    </customValue>
    <customValue>
        <fullName>Allocation Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Peer Review</fullName>
    </customValue>
    <customValue>
        <fullName>Jurisdiction Checklist</fullName>
    </customValue>
    <masterLabel>Case Item Type</masterLabel>
</GlobalValueSet>

classes/DRS_SetupData.cls
public class DRS_SetupData {
    
    public static final String ALLPROJECTS = 'ALL';
    public static final String DFSI_MRS_1703 = 'DFSI_MRS_1703';
    public static final String DFSI_MRS_1705 = 'DFSI_MRS_1705';
    public static final String DFSI_MRS_1706 = 'DFSI_MRS_1706';
    
    private static final String DEV = 'DEV';
    private static final String UAT = 'UAT';
    private static final String PROD = 'PROD';
    private static final String DEV_UAT = 'DEV_UAT';
    private static final String ALLENVIRONMENTS = 'DEV_UAT_PROD';
    
    private static Map<String, Profile> mapProfiles;
    private static Map<String, Id> mapRecordTypes;
    private static Map<String, Group> mapQueues;
    private static Map<String, DomainSite> mapDomainSites;
    private static Map<String, UserRole> mapUserRoles;
    private static List<String> currentProjects;
    private static String currentEnvironment;
    private static String currentEnvironmentSuffix;
    private static User adminUser;
    
    public static void processData() {
        System.debug('---DRS_SetupData:processData');
        List<String> listProjects = new List<String>();
        listProjects.add(DRS_SetupData.ALLPROJECTS);
        DRS_SetupData.processData(listProjects, DRS_SetupData.DEV_UAT);
    }
    
    public static void processData(String projectName, String environment) {
    	DRS_SetupData.processData(new List<String>{projectName}, environment);
    }
    
    public static void processData(List<String> listProjects, String environment) {
        System.debug('---DRS_SetupData:processData:listProjects:' + listProjects +', environment:' + environment);
        DRS_SetupData.currentProjects = listProjects;
        DRS_SetupData.currentEnvironment = environment;
        
        DRS_SetupData.initializeDRS_SetupData();
        DRS_SetupData.initializeCustomSettings();
        DRS_SetupData.initializeObjectData();
    }
    
    private static void initializeDRS_SetupData() {
        System.debug('---DRS_SetupData:initializeDRS_SetupData');
        String host = URL.getSalesforceBaseUrl().getHost();
        String suffix = '';
        if(host.left(2) == 'cs') {
            suffix = DRS_GlobalUtility.getGuid().left(8);
        }
        else {
            suffix = host.substringAfter('.');
        }
        DRS_SetupData.currentEnvironmentSuffix = suffix;
        
        DRS_SetupData.mapProfiles = new Map<String, Profile>();
        
        for(Profile objProfile : [
            Select Id, Name
            From Profile
        ]) {
            DRS_SetupData.mapProfiles.put(objProfile.Name, objProfile);
        }
        
        DRS_SetupData.mapRecordTypes = DRS_GlobalUtility.getRecordTypes();
        DRS_SetupData.mapQueues = new Map<String, Group>();
        for(Group objGroup : [SELECT Id, Name, DeveloperName, Email, Type FROM Group where Type='Queue']) {
            DRS_SetupData.mapQueues.put(objGroup.DeveloperName, objGroup);
        }
        
        for(User objUser : [Select Id From User Where UserName =: 'default.owner@dfsi.' + DRS_SetupData.currentEnvironmentSuffix + '.gov.au' And UserRoleId != null Limit 1]) {
            DRS_SetupData.adminUser = objUser;
        }
        if(adminUser == null) {
            for(User objUser : [Select Id From User Where Profile.Name = 'System Administrator' And UserRoleId != null Limit 1]) {
                DRS_SetupData.adminUser = objUser;
            }
        }
        
        DRS_SetupData.mapUserRoles = new Map<String,UserRole>();
        for(UserRole objUserRole : [Select Id, DeveloperName From UserRole Limit 1]) {
            DRS_SetupData.mapUserRoles.put(objUserRole.DeveloperName, objUserRole);
        }
        
        if(DRS_SetupData.adminUser == null) {
            DRS_SetupData.adminUser = new User(
        		ProfileId = DRS_SetupData.mapProfiles.get('System Administrator').Id,
        		UserRoleId = DRS_SetupData.mapUserRoles.values()[0].Id,
        		Username = 'default.owner@dfsi.' + DRS_SetupData.currentEnvironmentSuffix + '.gov.au',
        		FirstName = 'Default',
        		LastName = 'Owner',
        		CommunityNickname =  'Default' + DRS_GlobalUtility.getGuid().left(8),
        		Email = 'support@dfsi.gov.au',
        		Alias = DRS_GlobalUtility.getGuid().left(8),
        		TimeZoneSidKey = 'Australia/Sydney',
        		LocaleSidKey = 'en_AU',
        		EmailEncodingKey = 'ISO-8859-1',
        		LanguageLocaleKey = 'en_US'
            );
            Insert DRS_SetupData.adminUser;
        }
        
        DRS_SetupData.mapDomainSites = new Map<String, DomainSite>();
        for(DomainSite objDomainSite : [Select Id, SiteId, PathPrefix, DomainId, Domain.Domain From DomainSite]) {
            DRS_SetupData.mapDomainSites.put(objDomainSite.PathPrefix, objDomainSite);
        }
    }
    
    private static void initializeObjectData() {
        DRS_SetupData.initializeTaskTemplates();
    }
    
    private static void initializeCustomSettings(){
        System.debug('---DRS_SetupData:initializeCustomSettings');
        DRS_SetupData.initializeMRSCustomSettings();
    }
    
    private static Boolean isCurrentProjectEnvironment(String project, String environment) {
        System.debug('---DRS_SetupData:isCurrentProjectEnvironment:project:' + project + ', environment:' + environment);
        if(String.isNotBlank(environment) && (environment.contains(DRS_SetupData.currentEnvironment) || environment == DRS_SetupData.ALLENVIRONMENTS)) {
            for(String projectItem : DRS_SetupData.currentProjects) {
                if(projectItem == DRS_SetupData.ALLPROJECTS) {
                    return true;
                }
                else if(projectItem == project) {
                    return true;
                }
            }
        }
        
        return false;
    }
    
    private static void initializeTaskTemplates() {
        System.debug('---DRS_SetupData:initializeTaskTemplates');
        List<TaskTemplate__c> listTaskTemplates = new List<TaskTemplate__c>();
        
        if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1703, DRS_SetupData.ALLENVIRONMENTS)) {
            listTaskTemplates = new List<TaskTemplate__c>([
                Select Id
                From TaskTemplate__c
            ]);
            Delete listTaskTemplates;
            
            listTaskTemplates = new List<TaskTemplate__c>();
            listTaskTemplates.add(new TaskTemplate__c(Name = DRS_CaseService.InsurerReplyTaskType, Type__c = DRS_CaseService.InsurerReplyTaskType, CommunityPageURL__c = 'insurerform', Subject__c = DRS_CaseService.InsurerReplyTaskType, Description__c = DRS_CaseService.InsurerReplyTaskType, DaysUntilDueDate__c = 10));
            listTaskTemplates.add(new TaskTemplate__c(Name = DRS_CaseService.AdditionalInformationTaskType, Type__c = DRS_CaseService.AdditionalInformationTaskType, CommunityPageURL__c = 'additionalinfo', Subject__c = DRS_CaseService.AdditionalInformationTaskType, Description__c = DRS_CaseService.AdditionalInformationTaskType, DaysUntilDueDate__c = 10));
            listTaskTemplates.add(new TaskTemplate__c(Name = DRS_CaseService.JurisdictionChecklistTaskType, Type__c = DRS_CaseService.AllocationChecklistTaskType, CommunityPageURL__c = 'allocationchecklist', Subject__c = DRS_CaseService.JurisdictionChecklistTaskType, Description__c = DRS_CaseService.JurisdictionChecklistTaskType, DaysUntilDueDate__c = 10));
            listTaskTemplates.add(new TaskTemplate__c(Name = 'Update Case Team', Subject__c = 'Update Case Team and Primary Contact', Description__c = 'Please Assign Case Team Members for Internal MRS Staff, and set a Primary Contact, and then assign the Case to the Case.'));
            listTaskTemplates.add(new TaskTemplate__c(Name = 'Validate Insurer and Insurer Triage users', Subject__c = 'Validate Insurer', Description__c = 'Validate the correct Insurer has been selected by the applicant, and ensure that the Insurer selected has active Triage users associated with their account'));
            listTaskTemplates.add(new TaskTemplate__c(Name = 'Send Decision', Subject__c = 'Send Decision', Description__c = 'Email and Post Decision to parties.'));
        }
        if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1705, DRS_SetupData.ALLENVIRONMENTS)) {
			listTaskTemplates.add(new TaskTemplate__c(Name = 'MRS Assign to CMA', Subject__c = 'Assign Case to CMA', Description__c = 'Please assign the case back to the CMA once the decision has been sent. (This will be set as the Decision Sent Date)'));
			listTaskTemplates.add(new TaskTemplate__c(Name = 'MRS Decision', Subject__c = 'MRS Decision', Description__c = 'Please complete your Merit Review Decision. And Upload the final decision document/s to the Case Items section.'));
        }
        if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1706, DRS_SetupData.ALLENVIRONMENTS)) {
        	listTaskTemplates.add(new TaskTemplate__c(Name = DRS_CaseService.AllocationChecklistTaskType, Type__c = DRS_CaseService.JurisdictionChecklistTaskType, CommunityPageURL__c = 'jurisdictionchecklist', Subject__c = DRS_CaseService.AllocationChecklistTaskType, Description__c = DRS_CaseService.AllocationChecklistTaskType, DaysUntilDueDate__c = 10));
            listTaskTemplates.add(new TaskTemplate__c(Name = 'MRS Responded to App', Subject__c = 'Respond to App', Description__c = 'Please close this task once you have responded to the App (This will be set as the Respond to Date Sent)'));
        }
        if(listTaskTemplates.size() > 0) {
        	Insert listTaskTemplates;
        }
    }
    
    private static void initializeMRSCustomSettings() {
        System.debug('---DRS_SetupData:initializeMRSCustomSettings');
        Map<String, CaseTeamRoleAssociation__c> mapCaseTeamRoleAssociations = CaseTeamRoleAssociation__c.getall();
        Configuration__c objMRSConfiguration;
        try {
         objMRSConfiguration = DRS_GlobalUtility.getMRSConfiguration();
        }
        catch(Exception excep) { }
        
        if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1703, DRS_SetupData.ALLENVIRONMENTS) ||
           DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1705, DRS_SetupData.ALLENVIRONMENTS)) {
            if(mapCaseTeamRoleAssociations.size() > 0) {
                Delete mapCaseTeamRoleAssociations.values();
            }
            
            mapCaseTeamRoleAssociations = new Map<String, CaseTeamRoleAssociation__c>();
            mapCaseTeamRoleAssociations.put(
            	'Insurer_Claims_Manager_Claims_Manager',
            	new CaseTeamRoleAssociation__c(Name = 'Insurer_Claims_Manager_Claims_Manager', AccountType__c = 'Insurer', CaseTeamRole__c = 'Insurer Claims Manager', ContactRole__c = 'Claims Manager')
            );
            mapCaseTeamRoleAssociations.put(
            	'Insurer_Triager_Triage',
            	new CaseTeamRoleAssociation__c(Name = 'Insurer_Triager_Triage', AccountType__c = 'Insurer', CaseTeamRole__c = 'Insurer Triager', ContactRole__c = 'Triage')
            );
            mapCaseTeamRoleAssociations.put(
            	'Insurer_Legal_Rep_Legal_Rep',
            	new CaseTeamRoleAssociation__c(Name = 'Insurer_Legal_Rep_Legal_Rep', AccountType__c = 'Insurer', CaseTeamRole__c = 'Insurer Legal Rep', ContactRole__c = 'Legal Rep')
            );
            mapCaseTeamRoleAssociations.put(
            	'Insurer_Administrator',
            	new CaseTeamRoleAssociation__c(Name = 'Insurer_Administrator', AccountType__c = 'Insurer', CaseTeamRole__c = '', ContactRole__c = 'Administrator')
            );
            mapCaseTeamRoleAssociations.put(
            	'Legal_Firm_Legal_Rep',
            	new CaseTeamRoleAssociation__c(Name = 'Legal_Firm_Legal_Rep', AccountType__c = 'Legal Firm', CaseTeamRole__c = 'Legal Representative', ContactRole__c = 'Legal Rep')
            );
            Insert mapCaseTeamRoleAssociations.values();
        }
        
        if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1703, DRS_SetupData.ALLENVIRONMENTS) ||
           DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1705, DRS_SetupData.ALLENVIRONMENTS)) {
            if(objMRSConfiguration != null) {
                Delete objMRSConfiguration;
            }
               
               objMRSConfiguration = new Configuration__c();
               objMRSConfiguration.Name = 'Merit Review Services';
               objMRSConfiguration.CaseOwner__c = DRS_SetupData.mapQueues.get('Merit_Review_Service').Id;
               objMRSConfiguration.CommunityAccountOwner__c = adminUser.Id;
               objMRSConfiguration.DefaultTaskOwner__c = adminUser.Id;
               objMRSConfiguration.ProfileId1__c = DRS_SetupData.mapProfiles.get('MRS Applicant Community User').Id;
               objMRSConfiguration.ProfileId2__c = DRS_SetupData.mapProfiles.get('MRS Insurer Community User').Id;
               objMRSConfiguration.SiteId1__c = DRS_SetupData.mapDomainSites.get('/mrs01/s').SiteId;
               objMRSConfiguration.SiteId2__c = DRS_SetupData.mapDomainSites.get('/insurerlegal/s').SiteId;
               objMRSConfiguration.NumberOfDaysToExpire__c = 90;
               objMRSConfiguration.S3BucketName__c = 'prizmdocdata-test';
               objMRSConfiguration.S3EncryptionScheme__c = 'SHA-256';
               objMRSConfiguration.S3HeaderEncryptionScheme__c = 'AWS4-HMAC-SHA256';
               objMRSConfiguration.S3Host__c = 's3-ap-southeast-2.amazonaws.com';
               objMRSConfiguration.S3Region__c = 'ap-southeast-2';
               objMRSConfiguration.S3ServerSideEncryptionAlgorithm__c = 'AES256';
               objMRSConfiguration.S3Timeout__c = '10800';
               objMRSConfiguration.Username__c = 'Username';
               objMRSConfiguration.Password__c = 'Password';
               
               for(OrgWideEmailAddress objOrgWideEmailAddress : [Select Id From OrgWideEmailAddress Where DisplayName = 'State Insurance Regulatory Authority']) {
                   objMRSConfiguration.FromEmailAddress__c = objOrgWideEmailAddress.Id;
               }
               
               if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1706, DRS_SetupData.DEV)) {
                   objMRSConfiguration.EC2ServerPath__c = 'https://d1l96qz2fc0rch.cloudfront.net';
               }
               else if(DRS_SetupData.isCurrentProjectEnvironment(DRS_SetupData.DFSI_MRS_1706, DRS_SetupData.UAT)) {
                   objMRSConfiguration.EC2ServerPath__c = 'https://d2wy8o9xqmu45y.cloudfront.net';
               }
               
               Insert objMRSConfiguration;
        }
    }
    
}