objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCtrl.cls
public without sharing class TestCtrl {
    
    @AuraEnabled
    public static void updateCaseItem(String caseItemId) {
        for(CaseItem__c objCaseItem : [Select Id, Status__c From CaseItem__c Where Id =: caseItemId]) {
            if(objCaseItem.Status__c == 'Submitted') {
                objCaseItem.Status__c = DRS_CaseService.CaseItemStatusPending;
                Update objCaseItem;
            }
            objCaseItem.Status__c = 'Submitted';
            Update objCaseItem;
        }
    }
    
}