objects/Case.object
<CustomObject>
    <fields>
        <fullName>Insurer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Insurer Account Name</description>
        <label>Insurer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseItem__c.object
<CustomObject>
    <description>Case Item object for details related to cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Case for the Case Item</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Items</relationshipLabel>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Case Item</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user who submitted the Case Item</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CaseItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the Case Item</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CIN-{00000}</displayFormat>
        <label>Case Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>Claims Manager</fullName>
                </value>
                <value>
                    <fullName>Worker</fullName>
                </value>
                <value>
                    <fullName>Legal Rep</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Sole Practitioner</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                    <isActive>false</isActive>
                    <label>Lawyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TaskTemplate__c.object
<CustomObject>
    <description>A template object for creating tasks</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the task to be created using the template.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Case_Item_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Case_Item_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Application for merit review by SIRA form</fullName>
        <default>true</default>
        <label>Application for merit review by SIRA form</label>
    </customValue>
    <customValue>
        <fullName>Reply to an application for merit review by SIRA form</fullName>
    </customValue>
    <customValue>
        <fullName>Additional information request</fullName>
    </customValue>
    <customValue>
        <fullName>Allocation Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Peer Review</fullName>
    </customValue>
    <customValue>
        <fullName>Jurisdiction Checklist</fullName>
    </customValue>
    <masterLabel>Case Item Type</masterLabel>
</GlobalValueSet>

classes/DRS_Dashboard_CC_Test.cls
@IsTest
public class DRS_Dashboard_CC_Test {
    
    ///Initializes the SetupData
    @TestSetup
    private static void initializeData(){
        DRS_SetupData.processData();
    }
    
    ///Tests the whether the flag for delegated admin is returned for different users
    private static testmethod void testIsDelegatedAdmin() {
        Case objCase;
        Boolean isAdminUser;
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSubmitted();
        
        ///Test with delegated admin user
        Test.startTest();
        User objAdminUser = [Select Id, Contact.Name From User Where Contact.Role__c = 'Administrator' And IsActive = true Limit 1];
        System.runAs(objAdminUser) {
            isAdminUser = DRS_Dashboard_CC.isDelegatedAdmin();
        }
        Test.stopTest();
        
        System.assertEquals(true, isAdminUser);
        
        ///Test with non-delegated admin user
        User objNonAdminUser = [Select Id, Contact.Name From User Where Contact.Role__c != 'Administrator' And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objNonAdminUser) {
            isAdminUser = DRS_Dashboard_CC.isDelegatedAdmin();
        }
        
        System.assertEquals(false, isAdminUser);
    }
    
    ///Tests GetCaseItems as a Worker for Worker Case Item submitted
    private static testmethod void testGetCaseItems1() {
        Case objCase;
        String dashboardJSON;
        
        ///Submit a Worker Case Item
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSubmitted();
        
        ///Call GetCaseItem as a Worker
        Test.startTest();
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objWorkerUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(1, objDashboardJSON.openCaseItems.size());
        System.assertEquals(objCase.Id, objDashboardJSON.openCaseItems[0].caseId);
        System.assertEquals(objCase.CaseNumber, objDashboardJSON.openCaseItems[0].caseNumber);
        System.assertEquals(objWorkerUser.Contact.Name, objDashboardJSON.openCaseItems[0].submittedBy);
        System.assertEquals(objCase.Status, objDashboardJSON.openCaseItems[0].status);
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].communityPageURL));
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].remainingTimeToExpire));
    }
    
    ///Tests GetCaseItems as an Insurer for Worker Case Item submitted
    private static testmethod void testGetCaseItems2() {
        Case objCase;
        String dashboardJSON;
        
        ///Submit a Worker Case Item
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSubmitted();
        
        ///Call GetCaseItem as an Insurer
        Test.startTest();
        User objTriageUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleTriage And Contact.AccountId =: objCase.Insurer__c Limit 1];
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objTriageUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        TaskTemplate__c objInsurerReplyTemplate = DRS_CaseService.getTaskTemplateForType(DRS_CaseService.InsurerReplyTaskType);
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objTriageUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(0, objDashboardJSON.openCaseItems.size());
    }
    
    ///Tests GetCaseItems as a Worker for Insurer Case Item submitted
    private static testmethod void testGetCaseItems3() {
        Case objCase;
        String dashboardJSON;
        
        ///Submit an Insurer Case Item
        objCase = DRS_TestData.createCaseWithInsurerCaseItemSubmitted();
        
        ///Call GetCaseItem as a Worker
        Test.startTest();
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objWorkerUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(1, objDashboardJSON.openCaseItems.size());
        System.assertEquals(objCase.Id, objDashboardJSON.openCaseItems[0].caseId);
        System.assertEquals(objCase.CaseNumber, objDashboardJSON.openCaseItems[0].caseNumber);
        System.assertEquals(objWorkerUser.Contact.Name, objDashboardJSON.openCaseItems[0].submittedBy);
        System.assertEquals(objCase.Status, objDashboardJSON.openCaseItems[0].status);
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].communityPageURL));
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].remainingTimeToExpire));
    }
    
    ///Tests GetCaseItems as an Insurer for Insurer Case Item submitted
    private static testmethod void testGetCaseItems4() {
        Case objCase;
        String dashboardJSON;
        
        ///Submit an Insurer Case Item
        objCase = DRS_TestData.createCaseWithInsurerCaseItemSubmitted();
        
        ///Call GetCaseItem as an Insurer
        Test.startTest();
        User objTriageUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleTriage And Contact.AccountId =: objCase.Insurer__c Limit 1];
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objTriageUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objTriageUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(1, objDashboardJSON.openCaseItems.size());
        System.assertEquals(objCase.Id, objDashboardJSON.openCaseItems[0].caseId);
        System.assertEquals(objCase.CaseNumber, objDashboardJSON.openCaseItems[0].caseNumber);
        System.assertEquals(objWorkerUser.Contact.Name, objDashboardJSON.openCaseItems[0].submittedBy);
        System.assertEquals(objCase.Status, objDashboardJSON.openCaseItems[0].status);
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].communityPageURL));
        System.assert(String.isBlank(objDashboardJSON.openCaseItems[0].remainingTimeToExpire));
    }
    
    ///Tests GetCaseItems as a Worker for Worker Case Item "saved for later"
    private static testmethod void testGetCaseItems5() {
        Case objCase;
        String dashboardJSON;
        
        ///Save a Worker Case Item
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSaved();
        
        ///Call GetCaseItem as a Worker
        Test.startTest();
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objWorkerUser.Id, objDashboardJSON.userId);
        System.assertEquals(1, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(0, objDashboardJSON.openCaseItems.size());
        System.assertEquals(objCase.Id, objDashboardJSON.draftCaseItems[0].caseId);
        System.assertEquals(objCase.CaseNumber, objDashboardJSON.draftCaseItems[0].caseNumber);
        System.assertEquals(objWorkerUser.Contact.Name, objDashboardJSON.draftCaseItems[0].submittedBy);
        System.assertEquals(objCase.Status, objDashboardJSON.draftCaseItems[0].status);
        System.assert(String.isNotBlank(objDashboardJSON.draftCaseItems[0].communityPageURL));
        System.assert(String.isNotBlank(objDashboardJSON.draftCaseItems[0].remainingTimeToExpire));
    }
    
    ///Tests GetCaseItems as a Worker for Worker Case Item expired
    private static testmethod void testGetCaseItems6() {
        Case objCase;
        String dashboardJSON;
        
        ///Save a Worker Case Item
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSaved();
        
        ///Expire the saved Worker Case Item
        Test.startTest();
        for(CaseItem__c objCaseItem : objCase.CaseItems__r) {
            if(objCaseItem.Type__c == DRS_CaseService.WorkerCaseItemType) {
                objCaseItem.Status__c = DRS_CaseService.CaseItemStatusExpired;
                Update objCaseItem;
                break;
            }
        }
        
        ///Call GetCaseItem as a Worker
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();

        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objWorkerUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(0, objDashboardJSON.openCaseItems.size());
    }

    ///Tests GetCaseItems as a Worker for Case closed
    private static testmethod void testgetClosedCaseListJSON() {
        Case objCase;
        String dashboardJSON;
        
        ///Submit an Insurer Case Item
        objCase = DRS_TestData.createCaseWithInsurerCaseItemSubmitted();

        ///Update the status as Closed
        objCase.status = 'Closed';
        update objCase;
        
        ///Call GetCaseItem as a Worker
        Test.startTest();
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();

        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assert(objDashboardJSON != null);
        System.assertEquals(1, objDashboardJSON.closedCaseItems.size());
    }
    
    ///Tests DeleteDraftCaseItem as a Worker
    private static testmethod void testDeleteDraftCaseItem() {
        Case objCase;
        String dashboardJSON;
        
        ///Save a Worker Case Item
        objCase = DRS_TestData.createCaseWithWorkerCaseItemSaved();
        
        ///Call deleteDrafCaseItem as a Worker
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DRS_TestData.DRS_CalloutMock());
        User objWorkerUser = [Select Id, Contact.Name From User Where Contact.Role__c =: DRS_ContactService.ContactRoleWorker And ContactId =: objCase.ContactId Limit 1];
        System.runAs(objWorkerUser) {
            DRS_Dashboard_CC.deleteDrafCaseItem(objCase.Id);
            dashboardJSON = DRS_Dashboard_CC.getCaseItems();
        }
        Test.stopTest();
        
        ///Assert the returned arrays are as expected
        DRS_GlobalWrapper.DashboardJSON objDashboardJSON = (DRS_GlobalWrapper.DashboardJSON)JSON.deserialize(dashboardJSON, DRS_GlobalWrapper.DashboardJSON.class);
        System.assertEquals(objWorkerUser.Id, objDashboardJSON.userId);
        System.assertEquals(0, objDashboardJSON.draftCaseItems.size());
        System.assertEquals(0, objDashboardJSON.pendingCaseItems.size());
        System.assertEquals(0, objDashboardJSON.openCaseItems.size());
    }
}